# - _target_: models._utils.callbacks.TorchMetricsCallback
#   metrics:
#     # perplexity: 
#     #   _target_: torchmetrics.text.perplexity.Perplexity
#   - _target_: torchmetrics.text.perplexity.Perplexity
#   get_preds: 
#     _target_: models._core.decoder_llm.LLM_get_preds
#     _partial_: true
#   get_target: 
#     _target_: data._utils.llm.LLM_get_target
#     _partial_: true
#   write_path: 'metrics.csv'
#   hook_strings:
#   - "on_validation_start"
#   - "on_validation_epoch_end"
#   - "on_validation_batch_end"
- _target_: models._utils.binary_multitask_llm.example_labels_metrics_callback
  num_tasks: 4
  get_preds_and_target:
    _target_: models._utils.cb_llm.last_token_cb_llm_get_preds_and_target
    _partial_: true
# - _target_: models._utils.binary_multitask_llm.LLMBinaryMultitaskWritePredictions
#   hook_strings:
#   - on_validation_batch_end
# - _target_: models._utils.llm.WriteTokensCallback
#   tokenizer: 
#     _target_: data._core.tinystories.tinystories_tokenizer
#   hook_strings:
#   - on_validation_batch_end
#   - on_validation_epoch_end
#   - on_validation_epoch_start
- _target_: lightning.pytorch.callbacks.EarlyStopping
  patience: 3
  monitor: validation_loss
  mode: min
  verbose: true
- _target_: lightning.pytorch.callbacks.ModelCheckpoint
#  dirpath: '/home/fultonwang/Documents/code/experimental/results/vae/results/test/checkpoints'
#  monitor: validation_loss
  # every_n_train_steps: 600 #2000
  save_top_k: -1