_target_: data._core.tinystories.tinystories_cb_dataloader_with_julius_mix
orig_path: '/home/ubuntu/Documents/infembed/files/tinystories/TinyStoriesV2-GPT4-valid.txt'
julius_path: '/home/ubuntu/Documents/infembed/files/tinystories/TinyStories-valid-with-concepts.csv'
num_concepts: 4
max_len: 512
batch_size: 40
julius_start_num: 73636
julius_end_num: null