- _target_: models._utils.callbacks.DecoderCallback
  eos_token_id: 1
  max_len: 256
  hook_strings:
  - 'on_predict_batch_end'
  tokenizer:
    _target_: data._utils.character_tokenizer.CharacterTokenizer
    model_max_length: 256 