- _target_: models._utils.callbacks.GreedyDecoderCallback
  eos_token_id: 1
  max_len: 64
  hook_strings:
  - 'on_predict_batch_end'
  tokenizer:
    # _target_: data._utils.character_tokenizer.CharacterTokenizer
    # model_max_length: 64 
    _target_: data._utils.common.character_tokenizer