_target_: data._core.spotcheck.get_spotcheck_dataloader
path: '/spotcheck2/error_clustering/experiments/Supplement/Datasets/Blindspots/Synthetic/complex-${trial.trial}'
phase: 'test'
batch_size: 32
device: ${train_dataloader.device}
positive_only: false
limit: null
file_name_replace_prefix_from: '/data/users/fultonwang/error_clustering'
file_name_replace_prefix_to: '/spotcheck2/error_clustering'