_target_: torch.utils.data.DataLoader
dataset:
  _target_: 'data._utils.common.RandomSubset'
  dataset:
    _target_: torchvision.datasets.ImageNet
    root: '/home/ubuntu/Documents/infembed/files/imagenet'
    split: 'val'
  num: 5000
collate_fn: 
  _target_: data._core.imagenet.ImagenetCollateFn
  device: 'cuda:0'
batch_size: 128
shuffle: true
num_workers: 10