_target_: infembed.embedder._core.arnoldi_embedder.ArnoldiEmbedder
_partial_: true
loss_fn:
  _target_: torch.nn.CrossEntropyLoss
  reduction: 'sum'
projection_dim: 5
arnoldi_dim: 10
sample_wise_grads_per_batch: true
show_progress: true