_target_: infembed.embedder._core.gradient_embedder.GradientEmbedder
_partial_: true
loss_fn:
  _target_: torch.nn.CrossEntropyLoss
  reduction: 'sum'
sample_wise_grads_per_batch: true
show_progress: true