_target_: models._utils.common.load_model
model:
  _target_: models._core.decoder_llm.DecoderLightningModule
  decoder:
    _target_: models._core.decoder_llm.constructor
    model_dim: 32
    key_dim: 8
    value_dim: 8
    num_heads: 4
    num_layers: 2
    dropout: 0.1
    hidden_dim: 16
    num_tokens: 50257
    max_len: 500
eval: true
checkpoints_load_func: 
  _target_: models._utils.common.default_checkpoints_load_func
  key: state_dict
  # _target_: models._utils.common.lightning_checkpoints_load_func
  _partial_: true
checkpoint: '/home/ubuntu/Documents/infembed/examples/shakespeare/hydra_outputs/lightning_train/test/lr_0.01/lightning_logs/25hd2hwp/checkpoints/epoch=1-step=994.ckpt'
# _target_: models._utils.common.lightning_load_model
# load_from_checkpoint_fn: 
#   _target_: models._core.decoder_llm.DecoderLightningModule.load_from_checkpoint
#   _partial_: true
# path: '/home/ubuntu/Documents/infembed/examples/shakespeare/hydra_outputs/lightning_train/test/lr_0.01/lightning_logs/25hd2hwp/checkpoints/epoch=1-step=994.ckpt'
# eval: true