_target_: models._utils.common.load_model
model:
  _target_: models._core.cb_decoder_llm.CBDecoderLightningModule
  decoder:
    _target_: models._core.cb_decoder_llm.constructor
    model_dim: 768
    key_dim: 48
    value_dim: 48
    num_heads: 16
    num_layers: 4
    dropout: 0.0
    hidden_dim: 3072
    num_tokens: 10000
    max_len: 2048
    # num_concepts: 2
    num_concepts: 4
    concept_embedding_dim: 32
    concept_embedder_hidden_dims: null
    concept_generator_hidden_dims: null
    generator_hidden_dims: null
eval: true
checkpoints_load_func: 
  _target_: models._utils.common.default_checkpoints_load_func
  key: state_dict
  # _target_: models._utils.common.lightning_checkpoints_load_func
  _partial_: true
# checkpoint: '/home/ubuntu/Documents/infembed/examples/tinystories_cb/hydra_outputs/lightning_train/cb_simplified_read_julius_only_accum_2/lightning_logs/m0cfve7c/checkpoints/epoch=17-step=48000.ckpt'
# checkpoint: '/home/ubuntu/Documents/infembed/examples/tinystories_cb/hydra_outputs/lightning_train/cb_simplified_read_julius_only_accum_16/lightning_logs/p623gccj/checkpoints/epoch=8-step=8000.ckpt'
checkpoint: '/home/ubuntu/Documents/infembed/examples/tinystories_cb/hydra_outputs/lightning_train/cb_simplified_read_julius_only_accum_2/lightning_logs/ryp0s60u/checkpoints/epoch=1-step=1842.ckpt'
# checkpoint: null
# checkpoint: '/home/ubuntu/Documents/infembed/scripts/misc/lightning_logs/0hiuc53z/checkpoints/epoch=0-step=4500.ckpt'