_target_: torch.utils.data.DataLoader
dataset: 
  _target_: torchvision.datasets.ImageNet
  root: '/home/ubuntu/Documents/infembed/files/imagenet'
  split: 'val'
collate_fn: 
  _target_: data._core.imagenet.ImagenetCollateFn
  device: 'cuda:0'
batch_size: 128
num_workers: 10