_target_: data._core.spotcheck.get_spotcheck_dataloader
path: '/spotcheck/error_clustering/experiments/Supplement/Datasets/Blindspots/Synthetic/complex-${trial.trial}'
phase: 'train'
batch_size: 32
device: 'cuda:0'
positive_only: false
limit: null
file_name_replace_prefix_from: '/data/users/fultonwang/error_clustering'
file_name_replace_prefix_to: '/spotcheck/error_clustering'