_target_: models._core.decoder_llm.DecoderLightningModule
decoder:
  _target_: models._core.decoder_llm.constructor
  model_dim: 384
  key_dim: 64
  value_dim: 64
  num_heads: 6
  num_layers: 6
  dropout: 0.2
  hidden_dim: 256
  num_tokens: 107
  max_len: 256
loss_fn:
  _target_: models._core.decoder_llm.LabelSmoothingLoss
  criterion:
    _target_: torch.nn.KLDivLoss
    reduction: 'sum'
  smoothing: 0.1
configure_optimizers:
  _target_: models._utils.common.GenericConfigureOptimizers
  parameters_getter:
    _partial_: true
    _target_: models._utils.common.get_all_parameters
  optimizer_constructor:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 1e-3